#!/usr/bin/env ansible-playbook
# playbook for dba
---
# create user

- name: test createUser
  hosts: onetest
  user: root
  gather_facts: false
  vars:
  - user: "mongodb"
  - dbPort: 23333 
  - cacheSize: 5
  - compressMode: none
  
  tasks:
  - name: revoke chattr
    script: scripts/chattr_revoke.sh  
  
  - name: create mongodb {{ user }}
    user: name="{{ user }}"
  
  - name: grant  chattr
    script: scripts/chattr_grant.sh 
  
  - name: install mongodb 
    yum: >
      name=mongodb26
      update_cache=yes

  - name: create mongodb{{ dbPort }} instance dir
    file: path=/work/mongodb{{ dbPort }}     state=directory mode=0755
  - name: create mongodb{{ dbPort }} etc
    file: path=/work/mongodb{{ dbPort }}/etc state=directory mode=0755
  - name: create mongodb{{ dbPort }} key
    file: path=/work/mongodb{{ dbPort }}/key state=directory mode=0755
  - name: create mongodb{{ dbPort }} var
    file: path=/work/mongodb{{ dbPort }}/var state=directory mode=0755
  - name: create mongodb{{ dbPort }} log
    file: path=/work/mongodb{{ dbPort }}/log state=directory mode=0755
  - name: create mongodb{{ dbPort }} tmp
    file: path=/work/mongodb{{ dbPort }}/tmp state=directory mode=0755
  
  - name: copy mongodb{{ dbPort }}.conf config 
    template: src=templates/mongodb32.conf.j2 dest=/work/mongodb{{ dbPort }}/etc/mongodb{{ dbPort }}.conf mode=0644
  
  - name: copy keyFile
    template: src=files/keyFile dest=/work/mongodb{{ dbPort }}/key/keyFile mode=0400

  - name: start mongod
    shell: /usr/bin/numactl --interleave=all /opt/soft/mongodb3210/bin/mongod -f /work/mongodb{{ dbPort }}/etc/mongodb{{ dbPort }}.conf 

  - name: stop mongod
    shell: "kill -2 `cat /work/mongodb{{ dbPort }}/tmp/mongod.pid`"
